version: "3"
services:
  app_service:
    build: ./app/
    image: ltneric/ltn2018:latest
    volumes:
      - $PWD/log:/var/log/
    environment:
      - DEBUG="True"
    env_file:
      - secrets.env
