version: "3"
services:
    app_service:
        build: ./app/
        image: ltneric/ltn2017:latest
        volumes:
          #- $PWD/app:/app
          - $PWD/log:/var/log/
          #- $PWD/app/data/raw_data/:/app/data/raw_data/
        environment:
          - DEBUG="True"
        env_file:
          - secrets.env