version: "3"
services:
    app_service:
        build: ./app/
        image: ltneric/ltn2017:latest
        networks:
          - frontend
        volumes:
        #  - $PWD/app:/app
          - $PWD/tmp:/var/log/
        environment:
          - DEBUG=False
        env_file:
          - secrets.env
networks:
    frontend:
